<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-3LHL5QB2" failures="5" tests="10" name="Surefire test" time="19.955" errors="0" timestamp="2024-04-12T18:05:23 IST">
  <testcase classname="com.testcases.DatadrivenTest" name="readXlData" time="3.106"/>
  <testcase classname="com.testcases.DatadrivenTest" name="readXlData" time="1.36"/>
  <testcase classname="com.testcases.DatadrivenTest" name="readXlData" time="1.351"/>
  <testcase classname="com.testcases.DatadrivenTest" name="readXlData" time="1.31"/>
  <testcase classname="com.testcases.DatadrivenTest" name="readXlData" time="1.407"/>
  <testcase classname="com.testcases.DatadrivenTest" name="readSingleUser" time="1.506">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.testcases.DatadrivenTest.readSingleUser(DatadrivenTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- readSingleUser -->
  <testcase classname="com.testcases.DatadrivenTest" name="readSingleUser" time="2.304">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.testcases.DatadrivenTest.readSingleUser(DatadrivenTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- readSingleUser -->
  <testcase classname="com.testcases.DatadrivenTest" name="readSingleUser" time="2.468">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.testcases.DatadrivenTest.readSingleUser(DatadrivenTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- readSingleUser -->
  <testcase classname="com.testcases.DatadrivenTest" name="readSingleUser" time="1.733">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.testcases.DatadrivenTest.readSingleUser(DatadrivenTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- readSingleUser -->
  <testcase classname="com.testcases.DatadrivenTest" name="readSingleUser" time="1.363">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at com.testcases.DatadrivenTest.readSingleUser(DatadrivenTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- readSingleUser -->
</testsuite> <!-- Surefire test -->
